spring:
  application:
    name: spring-ai-1-poc

  ai:
    retry:
      max-attempts: 1
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-reasoner
          maxCompletionTokens: 5000

logging:
  level:
    root: INFO
    io.will.webfluxdemo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG
